name: Create Release on Sprint Branch Merge

on:
  push:
    branches:
      - develop

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if branch is sprint
        id: check_branch
        run: echo "::set-output name=is_sprint_branch::$(echo ${GITHUB_REF#refs/heads/} | grep -c '^sprint')"
        
      - name: Create release
        id: create_release
        run: |
          if [[ "${{ steps.check_branch.outputs.is_sprint_branch }}" == '1' ]]; then
            tag_name="sprint-${{ github.sha }}"
            release_name="Sprint Release - ${{ github.sha }}"
            release_body="This release is automatically created when a branch beginning with 'sprint' is merged into 'develop'."
            
            # Create the release using GitHub API
            response=$(curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/releases \
              --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              --header 'Content-Type: application/json' \
              --data "{
                \"tag_name\": \"$tag_name\",
                \"name\": \"$release_name\",
                \"body\": \"$release_body\",
                \"draft\": false,
                \"prerelease\": false
              }")
              
            release_id=$(echo $response | jq -r '.id')
            echo "Release created with ID: $release_id"
          else
            echo "Not a sprint branch. Skipping release creation."
          fi
