name: Create Release on Sprint Branch Merge

on:
  pull_request:
    branches:
      - 'develop*'
    types:
      - closed

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo branch name
        run: echo "current branch is ${GITHUB_REF##refs/heads/}"
        
      - name: Get branch name
        id: branch_name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Echo from env
        run: echo "${BRANCH_NAME}"

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'sprint*'
        with:
          files: |
            # Add files or directories to include in the release
            file-1.txt
            file-2.txt
          tag_name: sprint-${{ github.sha }}
          name: Sprint Release - ${{ github.sha }}
          body: |
            This release is automatically created when a branch beginning with 'sprint' is merged into 'develop'.
          draft: false
          prerelease: false
